# Generated by Django 4.2.10 on 2024-02-16 16:53

import apps.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productattribute_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="photos/product/categories",
                validators=[apps.products.validators.validate_icon],
                verbose_name="icon",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="photos/product/ingredients",
                validators=[apps.products.validators.validate_icon],
                verbose_name="icon",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="photos/product/tags",
                validators=[apps.products.validators.validate_icon],
                verbose_name="icon",
            ),
        ),
    ]
