# Generated by Django 4.2.10 on 2024-02-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new_product",
            field=models.BooleanField(default=True, verbose_name="New product"),
        ),
    ]
