# Generated by Django 4.2.7 on 2024-02-07 14:24

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.BigIntegerField(
                unique=True,
                validators=[apps.users.validators.check_phone_number_uz],
                verbose_name="Phone number",
            ),
        ),
    ]
